name: tests
on:
  push:
  pull_request:

jobs:
  precommit:
    name: pre-commit
    runs-on: ubuntu-latest
    timeout-minutes: 150
    steps:
    - uses: easimon/maximize-build-space@v10
      with:
          root-reserve-mb: 24000
          swap-size-mb: 1024
          remove-dotnet: 'true'
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'
    - run: 'pip install pre-commit'
    - run: 'pre-commit run --all'
    - run: 'git submodule update --init agnos-kernel-sdm845'
    - run: './tools/extract_tools.sh'
    - run: 'chmod u+x setup_python27.sh && sudo ./setup_python27.sh'
    - run: './build_kernel.sh'
    - run: 'export http_proxy="" && export https_proxy="" && export HTTP_PROXY="" && export HTTPS_PROXY="" && export no_proxy="gitlab.com" export NO_PROXY="gitlab.com"'
    - run: 'sudo ./build_system.sh'
